### ISSUE TITLE
Getting 403

### ISSUE THREAD

**Issue by huebnerk** [cloudflare/nginx-google-oauth#3]
Hi, thanks for this piece of work. It seems to be exactly waht I'm looking for.
Unfortunately I cannot get it to work.
I get the redirect to accounts.google.com but on the way back it seems to crash (sorry for not being more precise...)

I get an 403 and this in the logs

ccess.lua:202: authorize(): got error during access token request: no resolver defined to resolve "accounts.google.com", ...

I've got no idea what that means.

**Comment by huebnerk** [comment]
Thank you very much for your quick and helpful answer!
Your help made me make it work :-)

**Comment by shashankshandilya** [comment]
accounts.google.com could not be resolved (110: Operation timed out), I am still getting this error irrespective of putting resolver in configuration

**Comment by b-0-b** [comment]
I know this is an old issue and hopefully everyone has found a solution by now...

I am not using the Docker image. I encountered 403 errors because of a few settings where not correctly set.

I found the best place to get information on the problem was the nginx logs.

**Error**
`[error] 29913#29913: *6751 lua ssl certificate verify error: (20: unable to get local issuer certificate)`
**Solution**
Add these lines or similar. This was on a Debian 8 machine. I put them in my vhosts file.
```
  lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
  lua_ssl_verify_depth 3;

```
**Error**
`[crit] 29913#29913: *7083 connect() to [2a00:1450:4009:814::200d]:443 failed (99: Cannot assign requested address)`
**Solution**
IPv6 DNS does not work in my network. I put this in my vhosts file.
```
  resolver 10.0.0.71 10.0.0.80 10.0.0.99 ipv6=off;
```
